### ISSUE TITLE
Installation error when trying to update to the new version of meshtastic-node-red 2.2.15-3

### ISSUE THREAD

**Issue by Kollensperger** [scruplelesswizard/meshtastic-node-red#3] opened 2023-12-10 11:50 UTC
Currently trying to install the updated  meshtastic-node-red vi the palette or via pnpm throws the following error:

 ` ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@buf%2Fmeshtastic_protobufs.bufbuild_es: Not Found - 404
This error happened while installing the dependencies of @meshtastic/meshtasticjs@2.2.15-1
@buf/meshtastic_protobufs.bufbuild_es is not in the npm registry, or you have no permission to fetch it.
No authorization header was set for the request.
Progress: resolved 4, reused 0, downloaded 3, added 0`

**Comment by scruplelesswizard** [comment] 2023-12-11 17:47
Thanks for the report!
I'm closing this as a duplicate of [meshtastic/node-red-contrib-meshtastic/#15](https://github.com/meshtastic/node-red-contrib-meshtastic/issues/15), please see [my response](https://github.com/meshtastic/node-red-contrib-meshtastic/issues/15#issuecomment-1850569412) there.

**Closed as completed by scruplelesswizard** 2023-12-11 17:47 UTC
